import { NextRequest } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { vibeEngineSchema } from "@/lib/validation/schemas";
import { createApiError, createApiSuccess } from "@/lib/utils";
import { auth } from "@/lib/auth/config";
import { DEMO_TRACKS } from "@/lib/music/demo-catalog";
import { Track } from "@/types";

export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    const body = await req.json();
    const parsed = vibeEngineSchema.safeParse(body);

    if (!parsed.success) {
      return createApiError("Invalid Vibe Engine parameters", 400);
    }

    const { mood, energy, genre, durationMinutes } = parsed.data;

    let candidateTracks: Track[] = [];

    // Try DB first
    try {
      const dbTracks = await prisma.track.findMany({
        include: {
          artist: true,
          album: true,
          genres: { include: { genre: true } },
        },
        orderBy: { playCount: "desc" },
        take: 50,
      });

      if (dbTracks.length > 0) {
        candidateTracks = dbTracks.map((t) => ({
          ...t,
          genres: t.genres.map((g) => g.genre),
        })) as unknown as Track[];
      }
    } catch {
      // Ignore DB errors
    }

    // Fallback to DEMO_TRACKS if DB is empty
    if (candidateTracks.length === 0) {
      candidateTracks = DEMO_TRACKS;
    }

    // Filter candidate tracks based on energy and mood
    let filtered = candidateTracks.filter((t) => {
      const trackEnergy = t.energy ?? 0.5;
      const trackGenres = t.genres || [];

      // Energy filter
      if (energy === "high" && trackEnergy < 0.7) return false;
      if (energy === "low" && trackEnergy > 0.65) return false;
      if (energy === "medium" && (trackEnergy < 0.5 || trackEnergy > 0.85)) return false;

      // Mood / genre filter
      if (mood === "workout" || mood === "energetic") {
        const matches = trackGenres.some((g) => ["workout", "pop", "rock"].includes(g.slug)) || trackEnergy >= 0.8;
        if (!matches) return false;
      } else if (mood === "night") {
        const matches = trackGenres.some((g) => ["night", "romantic", "rock"].includes(g.slug));
        if (!matches) return false;
      } else if (mood === "focus") {
        const matches = trackGenres.some((g) => ["focus", "chill", "bollywood"].includes(g.slug)) || trackEnergy <= 0.65;
        if (!matches) return false;
      } else if (mood === "chill") {
        const matches = trackGenres.some((g) => ["chill", "romantic", "focus"].includes(g.slug)) || trackEnergy <= 0.65;
        if (!matches) return false;
      } else if (mood === "romantic") {
        const matches = trackGenres.some((g) => ["romantic", "bollywood"].includes(g.slug));
        if (!matches) return false;
      }

      if (genre && genre !== "all") {
        const hasGenre = trackGenres.some((g) => g.slug === genre);
        if (!hasGenre) return false;
      }

      return true;
    });

    if (filtered.length < 4) {
      // If too restrictive, filter only by energy
      if (energy === "high") {
        filtered = candidateTracks.filter((t) => (t.energy ?? 0.5) >= 0.7);
      } else if (energy === "low") {
        filtered = candidateTracks.filter((t) => (t.energy ?? 0.5) <= 0.7);
      } else {
        filtered = candidateTracks;
      }
    }

    if (filtered.length < 4) {
      filtered = candidateTracks;
    }

    // Shuffle
    const pool = [...filtered].sort(() => Math.random() - 0.5);

    // Select tracks until target duration is met (or at least 8 tracks)
    const targetSeconds = (durationMinutes || 30) * 60;
    let accumulatedSeconds = 0;
    const selectedTracks: Track[] = [];

    for (const track of pool) {
      selectedTracks.push(track);
      accumulatedSeconds += track.duration;
      if (accumulatedSeconds >= targetSeconds && selectedTracks.length >= 6) break;
    }

    // If pool was small, ensure at least 6-10 tracks
    if (selectedTracks.length < 6 && pool.length > 0) {
      for (const track of candidateTracks) {
        if (!selectedTracks.some((st) => st.id === track.id)) {
          selectedTracks.push(track);
          if (selectedTracks.length >= 8) break;
        }
      }
    }

    // Optionally save as playlist if user is logged in
    let savedPlaylist = null;
    if (session?.user?.id && req.nextUrl.searchParams.get("save") === "true") {
      try {
        savedPlaylist = await prisma.playlist.create({
          data: {
            name: `${mood.toUpperCase()} • ${energy.toUpperCase()} Vibe`,
            description: `Generated by VYBEON Vibe Engine for ${durationMinutes} mins of ${mood} vibe.`,
            userId: session.user.id,
            isGenerated: true,
            mood: mood,
            totalTracks: selectedTracks.length,
          },
        });
      } catch {
        // Ignore DB save errors
      }
    }

    return createApiSuccess({
      mood,
      energy,
      genre,
      durationMinutes,
      totalDurationSeconds: accumulatedSeconds,
      tracks: selectedTracks,
      savedPlaylist,
    });
  } catch (error) {
    console.error("Vibe Engine error:", error);
    const sample = [...DEMO_TRACKS].sort(() => Math.random() - 0.5).slice(0, 8);
    return createApiSuccess({
      mood: "curated",
      energy: "high",
      genre: "bollywood",
      durationMinutes: 30,
      totalDurationSeconds: 1800,
      tracks: sample,
      savedPlaylist: null,
    });
  }
}
