import { NextRequest } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { vibeEngineSchema } from "@/lib/validation/schemas";
import { createApiError, createApiSuccess } from "@/lib/utils";
import { auth } from "@/lib/auth/config";

export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    const body = await req.json();
    const parsed = vibeEngineSchema.safeParse(body);

    if (!parsed.success) {
      return createApiError("Invalid Vibe Engine parameters", 400);
    }

    const { mood, energy, genre, durationMinutes } = parsed.data;

    // Energy thresholds
    let minEnergy = 0;
    let maxEnergy = 1;
    if (energy === "low") {
      minEnergy = 0;
      maxEnergy = 0.45;
    } else if (energy === "medium") {
      minEnergy = 0.4;
      maxEnergy = 0.75;
    } else if (energy === "high") {
      minEnergy = 0.7;
      maxEnergy = 1.0;
    }

    // Valence thresholds depending on mood
    let minValence = 0;
    let maxValence = 1;
    if (mood === "happy" || mood === "workout" || mood === "energetic") {
      minValence = 0.5;
    } else if (mood === "rainy" || mood === "night") {
      maxValence = 0.6;
    }

    const whereClause: Record<string, unknown> = {
      energy: { gte: minEnergy, lte: maxEnergy },
      valence: { gte: minValence, lte: maxValence },
    };

    if (genre && genre !== "all") {
      whereClause.genres = {
        some: {
          genre: {
            slug: genre,
          },
        },
      };
    }

    let candidateTracks = await prisma.track.findMany({
      where: whereClause,
      include: {
        artist: true,
        album: true,
        genres: { include: { genre: true } },
      },
      orderBy: { playCount: "desc" },
      take: 40,
    });

    // If query was too narrow, loosen energy/valence requirements
    if (candidateTracks.length < 5) {
      candidateTracks = await prisma.track.findMany({
        include: {
          artist: true,
          album: true,
          genres: { include: { genre: true } },
        },
        orderBy: { playCount: "desc" },
        take: 30,
      });
    }

    // Select tracks until target duration (in seconds) is met
    const targetSeconds = durationMinutes * 60;
    let accumulatedSeconds = 0;
    const selectedTracks = [];

    // Shuffle pool first
    const pool = [...candidateTracks].sort(() => Math.random() - 0.5);

    for (const track of pool) {
      selectedTracks.push({
        ...track,
        genres: track.genres.map((g) => g.genre),
      });
      accumulatedSeconds += track.duration;
      if (accumulatedSeconds >= targetSeconds) break;
    }

    // Optionally save as playlist if user is logged in
    let savedPlaylist = null;
    if (session?.user?.id && req.nextUrl.searchParams.get("save") === "true") {
      savedPlaylist = await prisma.playlist.create({
        data: {
          name: `${mood.toUpperCase()} • ${energy.toUpperCase()} Vibe`,
          description: `Generated by VYBEON Vibe Engine for ${durationMinutes} mins of ${mood} vibe.`,
          userId: session.user.id,
          isGenerated: true,
          mood: mood,
          totalTracks: selectedTracks.length,
          tracks: {
            create: selectedTracks.map((t, idx) => ({
              trackId: t.id,
              position: idx + 1,
            })),
          },
        },
      });
    }

    return createApiSuccess({
      mood,
      energy,
      genre,
      durationMinutes,
      totalDurationSeconds: accumulatedSeconds,
      tracks: selectedTracks,
      savedPlaylist,
    });
  } catch (error) {
    console.error("Vibe Engine error:", error);
    return createApiError("Vibe Engine failed to generate vibe", 500);
  }
}
